const VN = {
  SIGN_OUT: 'Đăng xuất',
  CONFIRM_SIGN_OUT: 'Bạn có chắc chắn muốn đăng xuất khỏi tài khoản này?',
  GENERAL_INFOR: 'Thông tin chung',
  EMAIL: 'Email',
  USER_SCOPE: 'Vai trò',
  EDIT: 'Chỉnh sửa',
  PERSONAL_INFOR: 'Thông tin cá nhân',
  SURNAME: 'Họ và tên đệm',
  NAME: 'Tên',
  PHONE: 'Số điện thoại',
  CHANGE_PASSWORD: 'Đổi mật khẩu',
  SETUP: 'Cài đặt',
  CANCEL: 'Hủy bỏ',
  SURE: 'Chắc chắn',

  SWITCH_DEVICE: 'Bật/Tắt thiết bị',
  SWITCH_DEVICE_DESC: 'Ghi nhận quá trình bật/tắt thiết bị',
  SEARCH_DEVICE: 'Tra cứu thiết bị',
  SEARCH_DEVICE_DESC: 'Tra cứu thong tin lich sử ghi nhận',
  MAINTAIN_DEVICE: 'Bảo trì thiết bị',
  MAINTAIN_DEVICE_DESC: 'Ghi nhận thông tin bảo trì',
  LIQUIDATE_DEVICE: 'Thanh lý thiết bị',
  LIQUIDATE_DEVICE_DESC: 'Ghi nhận thông tin thanh lý',
  ACCOUNT_DEVICE: 'Kiểm kể thiết bị',
  ACCOUNT_DEVICE_DESC: 'Ghi nhận kiểm kê thiết bị',

  DEVICE_INFO: 'Thông tin thiết bị',
  DEVICE_TITLE: 'Tên thiết bị',
  MODEL: 'Mẫu thiết bị',
  MANUFACTURER: 'Công ty sản xuất',
  ACTIVE_STATE: 'Trạng thái hoạt động',
  MANUFACTURED_YEAR: 'Năm sản xuất',
  ORIGIN: 'Xuất xứ',
  START_USE_TIME: 'Năm đưa vào sử dụng',
  START_USE_STATE: 'Trạng thái khi đưa vào sử dụng',
  ORIGINAL_PRICE: 'Giá thành ban đầu',
  CURRENT_PRICE: 'Giá thành hiện tại',
  FACULTY: 'Bộ phận',
  AVAILABILITY: 'Hiện trạng khả dụng',
  STATE_ON: 'Bật',
  STATE_OFF: 'Tắt',
  NEW: 'Mới',
  USED: 'Cũ',
  TURN_ON: 'Bật thiết bị',
  TURN_OFF: 'Tắt thiết bị',
  REPORT_STATE: 'Báo cáo lỗi trạng thái',
  HISTORY_ACTIVITY: 'Lịch sử hoạt động',
  MAINTAIN_INFO: 'Thông tin bảo trì',
  RECORD_START_MAINTAIN: 'Ghi nhận bắt đầu bảo trì',
  RECORD_END_MAINTAIN: 'Ghi nhận kết thúc bảo trì',
  MAINTAIN_COMPANY: 'Đơn vị bảo trì',
  ADDRESS: 'Địa chỉ',
  MAINTAIN_COST: 'Chi phí bảo trì',
  NOTE: 'Ghi chú',
  UPDATE_MAINTAIN: 'Cập nhật bảo trì',
  LIQUIDATE_COMPANY: 'Đơn vị mua',
  LIQUIDATE_PRICE: 'Giá trị thanh lý',
  LIQUIDATE: 'Thanh lý'
};

export { VN };
